### ISSUE TITLE
XML version supported?

### ISSUE THREAD

**Issue by saona-raimundo** [faassen/xot#10]
Hi! Thanks for the crate!

I just wanted to know better what version of XML is supported (1.0 or 1.1).
Could we document this?
If version 1.0 is supported, would you consider moving to 1.1?

**Comment by faassen** [comment]
This crate relies on the xmlparser crate, which supports XML 1.0. 

I am open to considering XML 1.1 but at least parsing relies on that crate, so it would need to gain support.

**Comment by saona-raimundo** [comment]
Thanks! 
Then, 
1. Could we add that we work only on XML 1.0 in the README?
2. Do you know that [`xmlparser` is archived in GitHub](https://github.com/RazrFalcon/xmlparser)? (Not that it will stop working, but just to be aware)

**Comment by faassen** [comment]
Yes, I need to update the README.

I didn't know xmlparser got archived, thanks for pointing that out. I think it got folded into the source code of roxmltree. 

That may make it worthwhile to explore other parsers, or even take a copy and put it  Xot itself.
