### ISSUE TITLE
Make the `Xot` type cloneable

### ISSUE THREAD

**Issue by lo48576** [faassen/xot#32]
Currently `Xot` type is not cloneable (at least in straightforward way through `Clone` trait).
This prevents copy-on-write modification of XML tree through `Rc<Xot>` or `Arc<Xot>` or distributing read-only tree manipulation jobs to many threads... It seems that users should do serialize-then-deserialize to clone the arena or to copy a tree into another arena.
Of course users would be recommended to use single `Xot` arena to manipulate multiple trees if possible, but sometimes it is not preferred due to the ownership-related problems.

It looks like `Xot` can be cloned safely by `Clone` trait since the code base forbids the use of `unsafe` (i.e. the internal data structure does not manage raw pointers).
However, the method `Xot::clone(&mut self, node: Node)` may conflict with `Clone::clone()` and make them quite inconvenient, so it should be renamed before providing `Clone for Xot`.
(In that sense `Xot::to_string(&self, node: Node)` is also somewhat confusing since it conflicts with well-known `ToString::to_string()`, but it won't be a problem for now since it is less likely for `Xot` to implement `Display` trait.)

**Comment by lo48576** [comment]
In #33 I used `clone_node` tentatively as the new name of `Xot::clone()`, but I do neither think this is the best name nor have strong opinion for the new name.
There is similar method `Xot::clone_with_prefixes(&mut self, node: Node)`, so maybe some other names will be preferred to make their names look consistent.

**Comment by faassen** [comment]
Hey, sorry I missed this issue. It makes sense to support cloning, though it does clone the whole arena. It will cost an API breakage but that should be okay.
