### ISSUE TITLE
remove dependencies vector-map and next-gen

### ISSUE THREAD

**Issue by coderedart** [faassen/xot#6]
Dependencies like `next-gen` and `vector-map` depend on `syn v1` crate. But most popular rust crates moved to `syn v2`. So, anytime you depend on `xot` crate , you are **probably** adding two different `syn` versions to your dependency tree. 

1. Having two versions of the same crate in your dependency tree is bad.
2. `syn` having long compile times makes it really bad. 
3. If `xot` uses miette (which depends on syn v2) in nearby future, then it will be really really really bad.

I am hoping that `xot` could remove these dependencies in favor of alternatives (even at the cost of slight runtime performance).

**Comment by faassen** [comment]
Thanks for pointing this out!

next-gen has alternatives I am aware of.

For vector-map somw digging is required. It's used to store XML attributes which are generally limited in number. But perhaps a hashmap implementation is fine.

**Comment by coderedart** [comment]
[litemap](https://lib.rs/crates/litemap) is great. It is used in `icu4x` which is maintained by the unicode organisation. So, it is guaranteed to be maintained for a while.

Ideally, like you said, using official std `BTreeMap` should be good enough in terms of cache locality. And we have one less dependency to worry about. litemap docs do state that the performance is similar above 12 elements for both containers.

**Comment by faassen** [comment]
On main I've now eliminated VecMap in favor of `BTreeMap`. The test still run and I don't expect much breakage in my own code that uses Xot.

Getting rid of `next-gen` is more tricky. The alternative with the same performance, `genawaiter`, has the exact same problem you mentioned, and also depends on syn v1.

Rewriting the various generators to plain Rust iterators isn't a very pleasant exercise and would likely make the code less maintainable.

For alternatives with less performance (which may be acceptable if it gets rid of syn v1), see also here: https://github.com/Tuupertunut/rust-generator-benchmark

**Comment by faassen** [comment]
vecmap-rs is now also removed. I've replaced next-gen with genawaiter on a whim, because the API was slightly nicer.
