### ISSUE TITLE
Top xml processing instruction lost

### ISSUE THREAD

**Issue by tomuxmon** [faassen/xot#8]
Hello. I am trying out your lib and had [great success so far](https://github.com/tomuxmon/xml-mut/tree/wip-xot) :), but I have stumbled upon one edge case. Best demonstrated with a test:

```rust
    #[test]
    fn test_top_xml_processing_instruction() {
        let mut xot = Xot::new();
        let original_xml = r#"<?xml version="1.0" encoding="utf-8"?><root/>"#;
        let root = xot.parse(original_xml).unwrap();
        assert_eq!(original_xml, xot.to_string(root).unwrap());
    }
```

this test fails and the result is as follows:

```
running 1 test
thread 'serializer::tests::test_top_xml_processing_instruction' panicked at src/serializer.rs:342:9:
assertion `left == right` failed
  left: "<?xml version=\"1.0\" encoding=\"utf-8\"?><root/>"
 right: "<root/>"
```

I was expecting `<?xml version=\"1.0\" encoding=\"utf-8\"?>` would still remain after calling `to_string`. Am I missing something?

**Comment by faassen** [comment]
There's now the ability to generate the XML declaration using the serialization parameters, so I think we can close this issue.
